### ISSUE TITLE
Could you please open-source your data? We want to follow your work.

### ISSUE THREAD

**Issue by beyondguo** [RandyZhouRan/MELM#2]
Hi, thanks for your great work *MELM: Data Augmentation with Masked Entity Language Modeling for Low-Resource NER*.

We are doing some work on augmentation for NER tasks, could you please open-source your data, so we can directly follow your work?
To be concret, could you please tell me how you sample the {100,200, ...} samples from the CONLL2002/2003 datasets? Are they the first 100/200 examples in the dataset?

**Comment by RandyZhouRan** [comment]
As explained in the original paper, the low-resource datasets were randomly sampled from the full CoNLL dataset.
