### ISSUE TITLE
您好，请问中文命名实体识别的数据集，的数据格式是怎样的？

### ISSUE THREAD

**Issue by studymryang** [RandyZhouRan/MELM#5]
我用了的是数据集格式是这样的。
海 O
钓 O
比 O
赛 O
地 O
点 O
在 O
厦 B-LOC
门 I-LOC
与 O
金 B-LOC
门 I-LOC
之 O
间 O
的 O
海 O
域 O
。 O
这 O
座 O
依 O
山 O
傍 O
水 O
的 O
博 O
物 O
馆 O
由 O
国 O
内 O
一 O
流 O
的 O
设 O
计 O
师 O
主 O
持 O
设 O
计 O
， O
整 O
个 O
建 O
筑 O
群 O
精 O
美 O
而 O
恢 O
宏 O
。 O
但是他会报错：
Traceback (most recent call last):
  File "trainer.py", line 172, in <module>
    train_dataloader = DataLoader(train_dataset, batch_size=BSIZE, sampler=RandomSampler(train_dataset))
  File "/home/ynau/miniconda3/envs/yn_nlp_one/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 98, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
但是，在每一句有空格的数据集中他就不会报错，类似下面的数据集
海 O
钓 O
比 O
赛 O
地 O
点 O
在 O
厦 B-LOC
门 I-LOC
与 O
金 B-LOC
门 I-LOC
之 O
间 O
的 O
海 O
域 O
。 O

这 O
座 O
依 O
山 O
傍 O
水 O
的 O
博 O
物 O
馆 O
由 O
国 O
内 O
一 O
流 O
的 O
设 O
计 O
师 O
主 O
持 O
设 O
计 O
， O
整 O
个 O
建 O
筑 O
群 O
精 O
美 O
而 O
恢 O
宏 O
。 O

**Comment by RandyZhouRan** [comment]
Hi, we did not experiment on Chinese NER dataset. In your case without space between sentences, I guess the entire input file was treated as one long sentence, which messed up the data loading. You may try to modifiy the code using full stop as sentence seperators, or add spaces in your dataset.
